[book]
authors = ["Omar Shehata"]
language = "en"
multilingual = false
src = "src"
title = "7 Second Surveys"

[output.html]
edit-url-template = "https://github.com/OmarShehata/7-second-surveys/edit/main/{path}"
fold = { enable = true, level = 0 }

[output.html.print]
enable = false 

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]