name: Build and Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up mdBook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.43/mdbook-v0.4.43-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin

      # Add verification step
      - name: Verify source files
        run: |
          echo "Repository contents:"
          ls -R
          echo "Checking SUMMARY.md exists:"
          test -f src/SUMMARY.md

      - name: Build with mdBook
        run: |
          bin/mdbook build
          echo "Built site contents:"
          ls -R book/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: book
          destination: /

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2